
# 配置服务端口
server:
  port: 8089

#配置连接数据库
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.163.com
    port: 465
    username: dataops_tony2016@163.com
    password: JFCBGJYAYALXLECY
  datasource:
    username: root
    password: Turing@2022
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog2?serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowMultiQueries=true
  # redis配置
  redis:
    host: 192.168.43.102
    port: 6379
    password: Turing@2022
    timeout: 10s
    lettuce:
      pool:
        max-active: 150
        max-wait: 5000ms
        max-idle: 100
        min-idle: 50

# config of rokectmq
rocketmq:
  name-server: 192.168.43.102:9876
  producer:
    group: turing-service-msg-exe_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

# mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.turing.springboot.dao.entity
  global-config:
    db-config:
      id-type: AUTO
      db-column-underline: true
      refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# mybatis-plus日志查询开启
logging:
  level:
    com.turing.springboot.dao.mapper: debug

# config of sa-token
sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 1800
  activity-timeout: -1
  auto-renew: false
  is-concurrent: true
  token-style: uuid
  is-share: false
  max-login-count: 20
  is-read-cookie: false
  is-read-body: false
  is-read-header: true
  is-log: false

# 线程池配置
thread:
  pool:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60



