
server:
  port: 8815

spring:
  application:
    name: springboot-admin
  datasource:
    username: root
    password: Turing@2022
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog2?serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowMultiQueries=true


# mybatis-plus:
mapper-locations: classpath:/mapper/*.xml
typeAliasesPackage: org.turing.admin.dao.entity
global-config:
  db-config:
    id-type: AUTO
    db-column-underline: true
    refresh-mapper: true
configuration:
  map-underscore-to-camel-case: true
  call-setters-on-nulls: true
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# mybatis-plus
logging:
  level:
    com.turing.springboot.dao.mapper: debug











