
server:
  port: 9011

spring:
  application:
    name: turing-blog${unique-name:}-service
  datasource:
    username: root
    password: Turing@2022
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog2?serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowMultiQueries=true
  # redis配置
  redis:
    host: 192.168.43.102
    port: 6379
    password: Turing@2022
    timeout: 10s
    lettuce:
      pool:
        max-active: 150
        max-wait: 5000ms
        max-idle: 100
        min-idle: 50
  # config of email: from email
  mail:
    host: smtp.163.com
    username: dataops_tony2016@163.com
    password: JFCBGJYAYALXLECY
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.43.102:8848
      password: nacos
      username: nacos

# config of rokectmq
rocketmq:
  name-server: 192.168.43.102:9876
  producer:
    group: turing-blog-service-msg-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

mybatis-plus:
  # mapper映射地址
  mapper-locations: classpath:mapper/*.xml
  # 实体类扫描包路径
  type-aliases-package: org.springcloud.turing.biz.dao.entity
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.example.mapper: debug

# 线程池配置
thread:
  pool:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60

# config of sa-token
sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 1800
  activity-timeout: -1
  auto-renew: false
  is-concurrent: true
  token-style: uuid
  is-share: false
  max-login-count: 20
  is-read-cookie: false
  is-read-body: false
  is-read-header: true
  is-log: false

# 第三方登录
oauth:
  gitee:
    client-id: 195f2c756c90dce902783e55545f5e99769f6c1a54fe60e47e26419d0474d506
    client-secret: c9489cedf24e4844b83d4e6945b771ea31418968e7a9335d51e36a6da1958476
    grant_type: authorization_code
    redirect-url: https://127.0.0.1:9012/oauth/login/gitee # Gitee回调地址
    access-token-url: https://gitee.com/oauth/token
    user-info-url: https://gitee.com/api/v5/user?access_token={access_token}
  github:
    client-id: Github的client-id
    client-secret: Github的client-secret
    redirect-url: https://你的前台域名/oauth/login/github #Github回调地址
    access-token-url: https://github.com/login/oauth/access_token
    user-info-url: https://api.github.com/user
  qq:
    app-id: QQ的APPID
    app-key: QQ的app_key
    grant_type: authorization_code
    redirect-url: https://你的前台域名/oauth/login/qq #QQ回调地址
    access-token-url: https://graph.qq.com/oauth2.0/token
    user-openid-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
    user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}

# 运行监控指标
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}



